### ISSUE TITLE
Converting SVG images

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_images#8]
There is a problem with the conversion of SVG files, it gives the following result: http://c2corgv6-demo.gis.internal:8480/active/1470394049_1761799458.png

The original SVG file should also be available, with it's converted JPG/PNG versions.

**Comment by tsauerwein** [comment]
Could you attach the svg file that you used for testing?

**Comment by asaunier** [comment]
See also https://github.com/c2corg/v6_api/issues/357 concerning SVG converting.

**Comment by ginold** [comment]
[bornes_camipro.svg.zip](https://github.com/c2corg/v6_images/files/403691/bornes_camipro.svg.zip)

**Comment by asaunier** [comment]
Any update concerning the support of SVG files? This is critical!
Do we still need to convert SVG images? Perhaps for thumbnails?

An example of a SVG image in v5:
http://www.camptocamp.org/images/208579/fr/face-n-des-grandes-jorasses-quelques-itineraires
=> the image is converted to JPEG but the original is an SVG: http://s.camptocamp.org/uploads/images/1336219429_894641918.svg

**Comment by fjacon** [comment]
@ginold what is the situation for V6 ? Can we upload SVG ?

**Comment by ginold** [comment]
well, nothing has changed - you can upload but the svg will be converted to a png file.

**Comment by asaunier** [comment]
Right, it's done here: https://github.com/c2corg/v6_images/blob/0cc2f4757f651de84b0e9aa7c9b0f8cd5de0c4e5/c2corg_images/views.py#L77-L86

Not sure converting SVG to PNG is relevant though because most of the time the SVG files are photos with routes drawn above => JPEG would be better. As in v5, for instance:
http://s.camptocamp.org/uploads/images/1336219429_894641918.svg
http://s.camptocamp.org/uploads/images/1336219429_894641918.jpg

Is the original SVG still available after the conversion? including in the image detail view?

**Comment by arnaud-morvan** [comment]
This is done and merged, closing

**Comment by asaunier** [comment]
Reopening because it seems the SVG are not taken into account as expected in the demo:
* they are converted to PNG (JPEG would make more sense)
* the original SVG file is not available
See https://github.com/c2corg/v6_ui/issues/944

**Comment by arnaud-morvan** [comment]
SVG files are correctly uploaded as SVG, but format detection returns PNG so the file extention is '.png'

**Comment by asaunier** [comment]
Is this change now available in demov6?

**Comment by asaunier** [comment]
Closing since the related changes were "ready for demo" before the golive and are now in production.
